server:
  port: 8082
  context-path: /
  tomcat:
    accesslog:
      directory: /wisdom/logs/housing-proprietor-webchat/
      enabled: true
      pattern: remote_addr=[%a] http_x_forward=[%{X-Forwarded-For}i] time=%t request=[%r] status=[%s] byte=[%b] elapsed=[%T] refer=[%{Referer}i] ua=[%{User-Agent}i] cookie=[]
      prefix: access_web
      suffix: .log
spring:
  cloud:
    consul:
      discovery:
        enabled: false
  jackson:
    date-format: dd-MM-yyyy
  application:
    index: "index.html"
  chain:
    strategy:
      content:
        enabled: true
        paths: /**
logging:
  config: classpath:log4j2.yml

feign:
    wisdom_housing_service: http://127.0.0.1:8081

weixin:
    AppID: wx4f6fa05baa6282e8
    AppSecret: b9ad756846b2f40b5be3ccf80d8ed496
    oauth2_url: https://open.weixin.qq.com/connect/oauth2/authorize
url:
    redirect_url: http://127.0.0.1:8082/api/redirect
app:
   url: http://127.0.0.1:8082


upload:
   face_path: /mnt/scImgs
   face_url: http://img.linlihouse.com/