spring:
  profiles:
    active: testing
  application:
    name: wisdom-proprietor-webchat
    index: index.html
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    deserialization:
      fail-on-unknown-properties: true
  aop:
    auto: true
  resources:
    chain:
      strategy:
        content:
          enabled: true
          paths: /**


